package quic

//go:generate sh -c "./mockgen_private.sh quic mock_send_conn_test.go github.com/fkwhite/quic-goV2 sendConn"
//go:generate sh -c "./mockgen_private.sh quic mock_sender_test.go github.com/fkwhite/quic-goV2 sender"
//go:generate sh -c "./mockgen_private.sh quic mock_stream_internal_test.go github.com/fkwhite/quic-goV2 streamI"
//go:generate sh -c "./mockgen_private.sh quic mock_crypto_stream_test.go github.com/fkwhite/quic-goV2 cryptoStream"
//go:generate sh -c "./mockgen_private.sh quic mock_receive_stream_internal_test.go github.com/fkwhite/quic-goV2 receiveStreamI"
//go:generate sh -c "./mockgen_private.sh quic mock_send_stream_internal_test.go github.com/fkwhite/quic-goV2 sendStreamI"
//go:generate sh -c "./mockgen_private.sh quic mock_stream_sender_test.go github.com/fkwhite/quic-goV2 streamSender"
//go:generate sh -c "./mockgen_private.sh quic mock_stream_getter_test.go github.com/fkwhite/quic-goV2 streamGetter"
//go:generate sh -c "./mockgen_private.sh quic mock_crypto_data_handler_test.go github.com/fkwhite/quic-goV2 cryptoDataHandler"
//go:generate sh -c "./mockgen_private.sh quic mock_frame_source_test.go github.com/fkwhite/quic-goV2 frameSource"
//go:generate sh -c "./mockgen_private.sh quic mock_ack_frame_source_test.go github.com/fkwhite/quic-goV2 ackFrameSource"
//go:generate sh -c "./mockgen_private.sh quic mock_stream_manager_test.go github.com/fkwhite/quic-goV2 streamManager"
//go:generate sh -c "./mockgen_private.sh quic mock_sealing_manager_test.go github.com/fkwhite/quic-goV2 sealingManager"
//go:generate sh -c "./mockgen_private.sh quic mock_unpacker_test.go github.com/fkwhite/quic-goV2 unpacker"
//go:generate sh -c "./mockgen_private.sh quic mock_packer_test.go github.com/fkwhite/quic-goV2 packer"
//go:generate sh -c "./mockgen_private.sh quic mock_mtu_discoverer_test.go github.com/fkwhite/quic-goV2 mtuDiscoverer"
//go:generate sh -c "./mockgen_private.sh quic mock_session_runner_test.go github.com/fkwhite/quic-goV2 sessionRunner"
//go:generate sh -c "./mockgen_private.sh quic mock_quic_session_test.go github.com/fkwhite/quic-goV2 quicSession"
//go:generate sh -c "./mockgen_private.sh quic mock_packet_handler_test.go github.com/fkwhite/quic-goV2 packetHandler"
//go:generate sh -c "./mockgen_private.sh quic mock_unknown_packet_handler_test.go github.com/fkwhite/quic-goV2 unknownPacketHandler"
//go:generate sh -c "./mockgen_private.sh quic mock_packet_handler_manager_test.go github.com/fkwhite/quic-goV2 packetHandlerManager"
//go:generate sh -c "./mockgen_private.sh quic mock_multiplexer_test.go github.com/fkwhite/quic-goV2 multiplexer"
//go:generate sh -c "./mockgen_private.sh quic mock_batch_conn_test.go github.com/fkwhite/quic-goV2 batchConn"
//go:generate sh -c "mockgen -package quic -self_package github.com/fkwhite/quic-goV2 -destination mock_token_store_test.go github.com/fkwhite/quic-goV2 TokenStore"
//go:generate sh -c "mockgen -package quic -self_package github.com/fkwhite/quic-goV2 -destination mock_packetconn_test.go net PacketConn"
